### ISSUE TITLE
HTML organization

### ISSUE THREAD

**Issue by Rodrigap** [hokerobert/prj-rev-bwfs-dasmoto#1]
https://github.com/hokerobert/prj-rev-bwfs-dasmoto/blob/4012de82dc14b1dd52b48e1062812f31eba16232/DasmotoArtsCrafts/index.html#L7-L21

Your HTML indentation is perfect, but I'd suggest removing the extra lines of blank space around each element. It makes your code harder to read quickly when there's so much empty space. Instead, I'd recommend adding comments, formatted like this:

`<!–– section header here ––>
`
You can add these comments to divide and label each section of code!

**Comment by hokerobert** [comment]
Once again, thank you @Rodrigap for the feedback! I thought the blank space would make the code easier to read for everyone.  Also, its a habit you pick up from writing in school or work (essays, creative writing, stories, emails, etc.).

With coding I will need to switch it up.  As of now I'm not sure if the approach for me will make it more efficient or easier to read.  I will cut down on the blank space for blocks of code for a specific function or purpose and include comments for better explanation and flow.

Thanks again!
