### ISSUE TITLE
Universal styles

### ISSUE THREAD

**Issue by Rodrigap** [hokerobert/prj-rev-bwfs-dasmoto#2]
https://github.com/hokerobert/prj-rev-bwfs-dasmoto/blob/4012de82dc14b1dd52b48e1062812f31eba16232/DasmotoArtsCrafts/resources/style.css#L16

Instead of writing "font-family: Helvetica;" in 7 different places, consider removing all those lines and instead using the universal body CSS selector to set the default font of the HTML body to helvetica! This will help reduce a lot of repetitive CSS and it looks a little more professional:

```
body {
  font-family: Helvetica;
}
```

**Comment by hokerobert** [comment]
Ahhhhhhh :) I should have read this before responding in the first comment.  Thank you  @Rodrigap!  This makes perfect sense!
