### ISSUE TITLE
Grade: Meets Expectations

### ISSUE THREAD

**Issue by Rodrigap** [hokerobert/prj-rev-bwfs-dasmoto#3]
Nice job on this project! Your HTML and CSS are both fully functional, your finished product looks great. I didn't have any major critiques about your code, just a couple of small suggestions. I'd highly recommend utilizing both HTML comments and CSS universal style selectors! It makes a big difference in the efficiency of your work. Other than that, great job! Remember that you're free to elaborate on the spec and add any extra sections or styling that you'd like to if you're feeling creative!

**Comment by hokerobert** [comment]
Thanks @Rodrigap  for the quick turnaround!  Appreciate the feedback as well!

I was debating on whether to use comments for this first submission or not.  In the end I chose the latter so I can focus on reviewing the finish product and thinking to myself the best approach.  But I think with things becoming more difficult I want to leave breadcrumbs to track my train of thought during coding. Will definitely will utilize the comment features more moving forward!

For CSS universal selectors do you mean using selectors that would apply to elements and attributes with the same value throughout the page?  If so, I will take a look back at the code and see where I can make it more efficient.

Thanks again!
